apiVersion: apps/v1
kind: Deployment
metadata:
  name: patrones_api
spec:
  selector:
    matchLabels:
      app: patrones_api
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: patrones_api
      spec:
        containers:
          - image: sergios21/patrones_api:latest
            name: patrones_api
            env:
              - name: DB_SERVER_IP
                value: mysql.main.svc.cluster.local.
            ports:
              - containerPort: 8080
                name: patrones_api
            readinessProbe:
              httpGet:
                path: /user/todos
                port: 8080
     