apiVersion: apps/v1
kind: Deployment
metadata:
  name: patrones-api
spec:
  strategy:          
    type: Recreate
  selector:
    matchLabels:
      app: patrones-api
  template:         
    metadata:
      labels:
        app: patrones-api
    spec:
      containers:
        - image: sergios21/patrones_api:latest
          name: patrones-api
          env:
            - name: DB_SERVER_IP
              value: mysql.main.svc.cluster.local.
          ports:
            - containerPort: 8080
              name: patrones-api
          readinessProbe:
            httpGet:
              path: /user/todos
              port: 8080
          resources:                    
            requests:
              cpu: "50m"               # Solicita 200 millicores de CPU
              memory: "138Mi"           # Solicita 256 MiB de memoria
            limits:
              cpu: "250m"              # Límite de hasta 1 CPU
              memory: "512Mi"           # Límite de hasta 512 MiB de memoria
