apiVersion: v1
kind: Service
metadata:
  name: api-service-loadbalancer
  labels:
    app: patrones_api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: patrones_api