apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: front-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: patrones-front     # El nombre del Deployment que queremos escalar
  minReplicas: 1             # Número mínimo de réplicas
  maxReplicas: 3            # Número máximo de réplicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Escalar si el uso de CPU promedio aumenta
